spring:
  application.name: bank
  profiles.active: profile3
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@data-5fv0k.mongodb.net/test?retryWrites=true
      database: Bank
#      authentication-database: admin
#      database: Bank
#      host: data-shard-00-00-5fv0k.mongodb.net
#      username: admin
#      password: admin
#      port: 27017 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server: 
  port: 8080

recipient:
  option: bank-b

  
  
---

spring:
  profiles: profile1
 
name:
  option: 1

address:
  option: full
 
---

spring:
  profiles: profile2

name:
  option: 1

address:
  option: partial
  
---

spring:
  profiles: profile3

name:
  option: 2

address:
  option: full
  
---

spring:
  profiles: profile4
  
name:
  option: 2

address:
  option: partial
