spring:
  application.name: bank
  profiles.active: profile3
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  #instance:
    #instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
server: 
  port: 8080

recipient:
  option: bank-b

  
  
---

spring:
  profiles: profile1
 
name:
  option: 1

address:
  option: full
 
---

spring:
  profiles: profile2

name:
  option: 1

address:
  option: partial
  
---

spring:
  profiles: profile3

name:
  option: 2

address:
  option: full
  
---

spring:
  profiles: profile4
  
name:
  option: 2

address:
  option: partial
